apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - image: $IMAGE
        name: result
        ports:
        - containerPort: 80
          name: result
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets
