apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - image: $IMAGE
        name: vote
        ports:
        - containerPort: 80
          name: vote
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets