apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - image: $IMAGE
        name: worker
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets