name: Build Result
# template source: https://github.com/dockersamples/.github/blob/main/templates/call-docker-build.yaml

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'

# Jobs
jobs:
  
  # Test and Build node.js image
  Build:

    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: result
    
    # Setup multiple node versions to test
    strategy:
      matrix:
        node: [14, 16, 18, 20]

    steps:
      - uses: actions/checkout@v5

      - name: node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: result/package-lock.json
      
      # Install npm dependencies before build
      - run: npm install
      - run: npm ci
      - run: npm test